<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-11-19T17:57:30+13:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Volunteer Wellington',
    'version_installed' => '5.7.5.13',
    'misc' => array(
        'access_entity_updated' => 1500267071,
        'latest_version' => '8.2.1',
        'do_page_reindex_check' => false,
    ),
    'mail' => array(
        'method' => 'php_mail',
    ),
    'cache' => array(
        'blocks' => true,
        'assets' => true,
        'theme_css' => true,
        'overrides' => true,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ),
    'debug' => array(
        'detail' => 'message',
        'display_errors' => false,
    ),
);
